*&---------------------------------------------------------------------*
*& Include          ZIN_BM_EX_BAPI_UPLOADF03
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form 9003_Accounting_Posting
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM 9003_ACCOUNTING_POSTING
  CHANGING
    LPT_FPAR_D TYPE ZTT_BM_EXBA_FPAR
    LPT_RETURN TYPE BAPIRET2_T
    LPW_DOCRS    TYPE ZTB_BM_EXBA_FPAR-DOCRS.

  DATA:
    LS_DOCUMENTHEADER TYPE  BAPIACHE09,
    LS_CUSTOMERCPD    TYPE  BAPIACPA09,
    LS_CONTRACTHEADER TYPE  BAPIACCAHD.

  DATA:
    LV_OBJ_TYPE TYPE  BAPIACHE09-OBJ_TYPE,
    LV_OBJ_KEY  TYPE  BAPIACHE09-OBJ_KEY,
    LV_OBJ_SYS  TYPE  BAPIACHE09-OBJ_SYS,
    LV_COMP     TYPE CHAR4,
    LV_DOCN     TYPE CHAR10,
    LV_YEAR     TYPE CHAR4.

  DATA:
    LT_ACCOUNTGL            TYPE TABLE OF BAPIACGL09, "G/L account item
    LT_ACCOUNTRECEIVABLE    TYPE TABLE OF BAPIACAR09, "Customer Item
    LT_ACCOUNTPAYABLE       TYPE TABLE OF  BAPIACAP09, "Vendor Item
    LT_ACCOUNTTAX           TYPE TABLE OF  BAPIACTX09, "Tax item
    LT_CURRENCYAMOUNT       TYPE TABLE OF  BAPIACCR09, "Currency Items
    LT_CRITERIA             TYPE TABLE OF  BAPIACKEC9, "CO-PA Account Assignment Characteristics
    LT_VALUEFIELD           TYPE TABLE OF  BAPIACKEV9, "CO-PA Account Assignment Value Fields
    LT_EXTENSION1           TYPE TABLE OF  BAPIACEXTC, "Container for 'Customer Exit' Parameter
    LT_RETURN               TYPE TABLE OF  BAPIRET2, "Return parameter
    LS_RETURN               TYPE BAPIRET2,
    LT_PAYMENTCARD          TYPE TABLE OF BAPIACPC09, "Payment Card Information
    LT_CONTRACTITEM         TYPE TABLE OF  BAPIACCAIT, "Additional Contract Accounts Recieviable and Payable Document Line Item
    LT_EXTENSION2           TYPE TABLE OF  BAPIPAREX, "Reference Structure for BAPI Parameters EXTENSIONIN/EXTENSIONOUT
    LT_REALESTATE           TYPE TABLE OF  BAPIACRE09, "Real Estate Account Assignment Data
    LT_ACCOUNTWT            TYPE TABLE OF BAPIACWT09, "Withholding tax information for FI Interface
    LT_ACC_DOC_ASSET_FIELDS TYPE TABLE OF ZST_ACC_DOC_ASSET_FIELDS. "Asset field

  PERFORM 9003_GET_ACC_PARAMS
  USING LPT_FPAR_D
  CHANGING LS_DOCUMENTHEADER
           LS_CUSTOMERCPD
           LS_CONTRACTHEADER
           LT_ACCOUNTGL
           LT_ACCOUNTRECEIVABLE
           LT_ACCOUNTPAYABLE
           LT_ACCOUNTTAX
           LT_CURRENCYAMOUNT
           LT_CRITERIA
           LT_VALUEFIELD
           LT_EXTENSION1
           LT_PAYMENTCARD
           LT_CONTRACTITEM
           LT_EXTENSION2
           LT_REALESTATE
           LT_ACCOUNTWT
           LT_ACC_DOC_ASSET_FIELDS.

*   Create data
  CALL FUNCTION 'BAPI_ACC_DOCUMENT_POST'
    EXPORTING
      DOCUMENTHEADER    = LS_DOCUMENTHEADER
      CUSTOMERCPD       = LS_CUSTOMERCPD
      CONTRACTHEADER    = LS_CONTRACTHEADER
    IMPORTING
      OBJ_TYPE          = LV_OBJ_TYPE
      OBJ_KEY           = LV_OBJ_KEY
      OBJ_SYS           = LV_OBJ_SYS
    TABLES
      ACCOUNTGL         = LT_ACCOUNTGL
      ACCOUNTRECEIVABLE = LT_ACCOUNTRECEIVABLE
      ACCOUNTPAYABLE    = LT_ACCOUNTPAYABLE
      ACCOUNTTAX        = LT_ACCOUNTTAX
      CURRENCYAMOUNT    = LT_CURRENCYAMOUNT
      CRITERIA          = LT_CRITERIA
      VALUEFIELD        = LT_VALUEFIELD
      EXTENSION1        = LT_EXTENSION1
      RETURN            = LT_RETURN
      PAYMENTCARD       = LT_PAYMENTCARD
      CONTRACTITEM      = LT_CONTRACTITEM
      EXTENSION2        = LT_EXTENSION2
      REALESTATE        = LT_REALESTATE
      ACCOUNTWT         = LT_ACCOUNTWT.

  LV_COMP = LV_OBJ_KEY+10(4).
  LV_DOCN = LV_OBJ_KEY+0(10).
  LV_YEAR = LV_OBJ_KEY+14(4).

  LPT_RETURN = LT_RETURN.
  LPW_DOCRS  = LV_COMP && LV_DOCN && LV_YEAR.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form 9003_GET_ACC_PARAMS
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*&      <-- LS_DOCUMENTHEADER
*&      <-- LS_CUSTOMERCPD
*&      <-- LS_CONTRACTHEADER
*&      <-- LT_ACCOUNTGL
*&      <-- LT_ACCOUNTRECEIVABLE
*&      <-- LT_ACCOUNTPAYABLE
*&      <-- LT_ACCOUNTTAX
*&      <-- LT_CURRENCYAMOUNT
*&      <-- LT_CRITERIA
*&      <-- LT_VALUEFIELD
*&      <-- LT_EXTENSION1
*&      <-- LT_PAYMENTCARD
*&      <-- LT_CONTRACTITEM
*&      <-- LT_EXTENSION2
*&      <-- LT_REALESTATE
*&      <-- LT_ACCOUNTWT
*&      <-- LT_ACC_DOC_ASSET_FIELDS
*&---------------------------------------------------------------------*
FORM 9003_GET_ACC_PARAMS
  USING LPT_FPAR_D TYPE ZTT_BM_EXBA_FPAR
  CHANGING
    LPS_DOCUMENTHEADER    TYPE BAPIACHE09
    LPS_CUSTOMERCPD       TYPE BAPIACPA09
    LPS_CONTRACTHEADER         TYPE BAPIACCAHD
    LPT_ACCOUNTGL         TYPE BAPIACGL09_TAB
    LPT_ACCOUNTRECEIVABLE TYPE BAPIACAR09_TAB
    LPT_ACCOUNTPAYABLE    TYPE BAPIACAP09_TAB
    LPT_ACCOUNTTAX        TYPE BAPIACTX09_TAB
    LPT_CURRENCYAMOUNT    TYPE BAPIACCR09_TAB
    LPT_CRITERIA          TYPE BAPIACKEC9_TAB
    LPT_VALUEFIELD        TYPE BAPIACKEV9_TAB
    LPT_EXTENSION1        TYPE BAPIACEXTC_TAB
    LPT_PAYMENTCARD       TYPE BAPIACPC09_TAB
    LPT_CONTRACTITEM      TYPE BAPIACCAIT_TAB
    LPT_EXTENSION2        TYPE BAPIPAREX_TAB
    LPT_REALESTATE        TYPE BAPIACRE09_TAB
    LPT_ACCOUNTWT         TYPE BAPIACWT09_TAB
    LPT_ACC_DOC_ASSET_FIELDS         TYPE GTY_ACC_DOC_ASSET_FIELDS.

  DATA:
    LR_DATA                 TYPE REF TO DATA,
    LS_BAPIPAREX            TYPE BAPIPAREX,
    LS_ACC_DOC_ASSET_FIELDS TYPE ZST_ACC_DOC_ASSET_FIELDS.

  LOOP AT LPT_FPAR_D INTO DATA(LS_FPAR_D).
    CASE LS_FPAR_D-PARAM.
      WHEN 'DOCUMENTHEADER'.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LPS_DOCUMENTHEADER.
      WHEN 'CUSTOMERCPD'.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LPS_CUSTOMERCPD.
      WHEN 'CONTRACTHEADER'.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LPS_CONTRACTHEADER.
      WHEN 'ACCOUNTGL'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACCOUNTGL.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACCOUNTGL.
      WHEN 'ACCOUNTRECEIVABLE'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACCOUNTRECEIVABLE.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACCOUNTRECEIVABLE.
      WHEN 'ACCOUNTPAYABLE'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACCOUNTPAYABLE.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACCOUNTPAYABLE.
      WHEN 'ACCOUNTTAX'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACCOUNTTAX.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACCOUNTTAX.
      WHEN 'CURRENCYAMOUNT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_CURRENCYAMOUNT.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_CURRENCYAMOUNT.
      WHEN 'CRITERIA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_CRITERIA.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_CRITERIA.
      WHEN 'VALUEFIELD'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_VALUEFIELD.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_VALUEFIELD.
      WHEN 'EXTENSION1'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_EXTENSION1.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_EXTENSION1.
      WHEN 'PAYMENTCARD'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PAYMENTCARD.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PAYMENTCARD.
      WHEN 'CONTRACTITEM'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_CONTRACTITEM.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_CONTRACTITEM.
      WHEN 'EXTENSION2'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_EXTENSION2.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_EXTENSION2.
      WHEN 'REALESTATE'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_REALESTATE.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_REALESTATE.
      WHEN 'ACCOUNTWT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACCOUNTWT.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACCOUNTWT.
      WHEN 'ZST_ACC_DOC_ASSET_FIELDS'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACC_DOC_ASSET_FIELDS.
        CALL TRANSFORMATION ID
          SOURCE XML LS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACC_DOC_ASSET_FIELDS.
      WHEN OTHERS.
    ENDCASE.
  ENDLOOP.


  " Header
  IF LPS_DOCUMENTHEADER-USERNAME IS INITIAL.
    LPS_DOCUMENTHEADER-USERNAME = SY-UNAME.
  ENDIF.

  " LPT_EXTENSION2
  LOOP AT LPT_ACC_DOC_ASSET_FIELDS INTO DATA(LS_ACC_DOC_ASSET_FIELDS_01).
    LS_BAPIPAREX-STRUCTURE  = 'ZST_ACC_DOC_ASSET_FIELDS'.
    LS_ACC_DOC_ASSET_FIELDS-POSNR = LS_ACC_DOC_ASSET_FIELDS_01-POSNR.
    LS_ACC_DOC_ASSET_FIELDS-ANBWA = LS_ACC_DOC_ASSET_FIELDS_01-ANBWA.
    LS_ACC_DOC_ASSET_FIELDS-BZDAT = LS_ACC_DOC_ASSET_FIELDS_01-BZDAT.
    LS_BAPIPAREX-VALUEPART1 = LS_ACC_DOC_ASSET_FIELDS.
    APPEND LS_BAPIPAREX TO LPT_EXTENSION2.
  ENDLOOP.
ENDFORM.
