*&---------------------------------------------------------------------*
*& Include          ZIN_BM_EX_BAPI_UPLOADF10
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form 9010_INCOMINGINVOICE_CREATE
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM 9010_INCOMINGINVOICE_CREATE
  CHANGING
    LPT_FPAR_D TYPE ZTT_BM_EXBA_FPAR
    LPT_RETURN TYPE BAPIRET2_T
    LPW_DOCRS    TYPE ZTB_BM_EXBA_FPAR-DOCRS.

  DATA:
    LS_HEADERDATA  TYPE  BAPI_INCINV_CREATE_HEADER,
    LS_ADDRESSDATA TYPE  BAPI_INCINV_CREATE_ADDRESSDATA,
    LS_OILDATA     TYPE  BAPI_INCINV_CREATE_OIL.

  DATA:
    LV_INVOICEDOCNUMBER TYPE BAPI_INCINV_FLD-INV_DOC_NO,
    LV_FISCALYEAR       TYPE BAPI_INCINV_FLD-FISC_YEAR.

  DATA:
    LT_ITEMDATA            TYPE TABLE OF BAPI_INCINV_CREATE_ITEM, "Item Data in Incoming Invoice
    LT_ACCOUNTINGDATA      TYPE TABLE OF BAPI_INCINV_CREATE_ACCOUNT, "Account Assignment Data in Incoming Invoice
    LT_GLACCOUNTDATA       TYPE TABLE OF BAPI_INCINV_CREATE_GL_ACCOUNT, "G/L Account Data at Invoice Receipt
    LT_MATERIALDATA        TYPE TABLE OF BAPI_INCINV_CREATE_MATERIAL, "Material Account Data in Incoming Invoice
    LT_TAXDATA             TYPE TABLE OF BAPI_INCINV_CREATE_TAX, "Tax Code in Incoming Invoice
    LT_WITHTAXDATA         TYPE TABLE OF BAPI_INCINV_CREATE_WITHTAX, "Withholding Tax Data in Incoming Invoice
    LT_VENDORITEMSPLITDATA TYPE TABLE OF BAPI_INCINV_CREATE_VENDORSPLIT, "Vendor Split in Incoming Invoice
    LT_EXTENSIONIN         TYPE TABLE OF BAPIPAREX, "Enhancement Fields (Import Parameter)
    LT_TM_ITEMDATA         TYPE TABLE OF BAPI_INCINV_CREATE_TM_ITEM, "Item Data Incoming Invoice for Transportation Management
    LT_NFMETALLITMS        TYPE TABLE OF /NFM/BAPIDOCITM, "BAPI Communication Structure NF Document Item Data
    LT_ASSETDATA           TYPE TABLE OF BAPI_INCINV_DETAIL_ASSET, "Return Messages
    LT_RETURN              TYPE TABLE OF BAPIRET2,
    LS_RETURN              TYPE BAPIRET2.


  PERFORM 9010_INCOMINGINVOICE_PARAMS
    USING LPT_FPAR_D
              CHANGING LS_HEADERDATA
                       LS_ADDRESSDATA
                       LS_OILDATA
                       LT_ITEMDATA
                       LT_ACCOUNTINGDATA
                       LT_GLACCOUNTDATA
                       LT_MATERIALDATA
                       LT_TAXDATA
                       LT_WITHTAXDATA
                       LT_VENDORITEMSPLITDATA
                       LT_EXTENSIONIN
                       LT_TM_ITEMDATA
                       LT_NFMETALLITMS
                       LT_ASSETDATA.

*   Create data
  CALL FUNCTION 'BAPI_INCOMINGINVOICE_CREATE'
    EXPORTING
      HEADERDATA          = LS_HEADERDATA
      ADDRESSDATA         = LS_ADDRESSDATA
      OILDATA             = LS_OILDATA
    IMPORTING
      INVOICEDOCNUMBER    = LV_INVOICEDOCNUMBER
      FISCALYEAR          = LV_FISCALYEAR
    TABLES
      ITEMDATA            = LT_ITEMDATA
      ACCOUNTINGDATA      = LT_ACCOUNTINGDATA
      GLACCOUNTDATA       = LT_GLACCOUNTDATA
      MATERIALDATA        = LT_MATERIALDATA
      TAXDATA             = LT_TAXDATA
      WITHTAXDATA         = LT_WITHTAXDATA
      VENDORITEMSPLITDATA = LT_VENDORITEMSPLITDATA
      RETURN              = LT_RETURN
      EXTENSIONIN         = LT_EXTENSIONIN
      TM_ITEMDATA         = LT_TM_ITEMDATA
      NFMETALLITMS        = LT_NFMETALLITMS
      ASSETDATA           = LT_ASSETDATA.


  LPT_RETURN = LT_RETURN.
  LPW_DOCRS  = LV_INVOICEDOCNUMBER && LV_FISCALYEAR.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form 9010_INCOMINGINVOICE_PARAMS
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*&      <-- LS_HEADERDATA
*&      <-- LS_ADDRESSDATA
*&      <-- LS_OILDATA
*&      <-- LT_ITEMDATA
*&      <-- LT_ACCOUNTINGDATA
*&      <-- LT_GLACCOUNTDATA
*&      <-- LT_MATERIALDATA
*&      <-- LT_TAXDATA
*&      <-- LT_WITHTAXDATA
*&      <-- LT_VENDORITEMSPLITDATA
*&      <-- LT_EXTENSIONIN
*&      <-- LT_TM_ITEMDATA
*&      <-- LT_NFMETALLITMS
*&      <-- LT_ASSETDATA
*&---------------------------------------------------------------------*
FORM 9010_INCOMINGINVOICE_PARAMS
  USING LPT_FPAR_D TYPE ZTT_BM_EXBA_FPAR
  CHANGING
    LPS_HEADERDATA  TYPE  BAPI_INCINV_CREATE_HEADER
    LPS_ADDRESSDATA TYPE  BAPI_INCINV_CREATE_ADDRESSDATA
    LPS_OILDATA     TYPE  BAPI_INCINV_CREATE_OIL
    LPT_ITEMDATA TYPE BAPI_INCINV_CREATE_ITEM_TAB
    LPT_ACCOUNTINGDATA TYPE BAPI_INCINV_CREATE_ACCOUNT_T
    LPT_GLACCOUNTDATA TYPE BAPI_INCINV_CREATE_GL_ACCT_T
    LPT_MATERIALDATA TYPE BAPI_INCINV_CREATE_MATERIAL_T
    LPT_TAXDATA TYPE BAPI_INCINV_CREATE_TAX_T
    LPT_WITHTAXDATA TYPE BAPI_INCINV_CREATE_WITHTAX_T
    LPT_VENDORITEMSPLITDATA TYPE BAPI_INCINV_CREATE_VENDORSP_T
    LPT_EXTENSIONIN TYPE BAPIPAREX_T
    LPT_TM_ITEMDATA TYPE TB_BAPI_INCINV_CREATE_TM_ITEM
    LPT_NFMETALLITMS TYPE /NFM/BAPIDOCITM_T
    LPT_ASSETDATA TYPE MRM_T_BAPI_INCINV_DETAIL_ASSET.

  DATA:
       LR_DATA TYPE REF TO DATA.

  LOOP AT LPT_FPAR_D INTO DATA(LPS_FPAR_D).
    CASE LPS_FPAR_D-PARAM.
      WHEN 'HEADERDATA'.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LPS_HEADERDATA.
      WHEN 'ADDRESSDATA'.
        CALL TRANSFORMATION ID
           SOURCE XML LPS_FPAR_D-XMLSTR
           RESULT DATA = LPS_ADDRESSDATA.
      WHEN 'OILDATA'.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LPS_OILDATA.
      WHEN 'ITEMDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ITEMDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ITEMDATA.
      WHEN 'ACCOUNTINGDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ACCOUNTINGDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ACCOUNTINGDATA.
      WHEN 'GLACCOUNTDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_GLACCOUNTDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_GLACCOUNTDATA.
      WHEN 'MATERIALDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_MATERIALDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_MATERIALDATA.
      WHEN 'TAXDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_TAXDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_TAXDATA.
      WHEN 'WITHTAXDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_WITHTAXDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_WITHTAXDATA.
      WHEN 'VENDORITEMSPLITDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_VENDORITEMSPLITDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_VENDORITEMSPLITDATA.
      WHEN 'EXTENSIONIN'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_EXTENSIONIN.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_EXTENSIONIN.
      WHEN 'TM_ITEMDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_TM_ITEMDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_TM_ITEMDATA.
      WHEN 'NFMETALLITMS'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_NFMETALLITMS.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_NFMETALLITMS.
      WHEN 'ASSETDATA'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ASSETDATA.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ASSETDATA.
      WHEN OTHERS.
    ENDCASE.
  ENDLOOP.
ENDFORM.
