*&---------------------------------------------------------------------*
*& Include          ZIN_BM_EX_BAPI_UPLOADF04
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*& Form 9004_PR_CREATE
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM 9004_PR_CREATE
  CHANGING
    LPT_FPAR_D TYPE ZTT_BM_EXBA_FPAR
    LPT_RETURN TYPE BAPIRET2_T
    LPW_DOCRS    TYPE ZTB_BM_EXBA_FPAR-DOCRS.

  DATA:
    LS_PRHEADER  TYPE  BAPIMEREQHEADER,
    LS_PRHEADERX TYPE  BAPIMEREQHEADERX.

  DATA:
    LV_NUMBER      TYPE  BAPIMEREQHEADER-PREQ_NO,
    LV_PRHEADEREXP TYPE  BAPIMEREQHEADER.

  DATA:
    LT_PRITEM                 TYPE TABLE OF BAPIMEREQITEMIMP,
    LT_PRITEMX                TYPE TABLE OF BAPIMEREQITEMX,
    LT_PRITEMEXP              TYPE TABLE OF BAPIMEREQITEM,
    LT_PRITEMSOURCE           TYPE TABLE OF BAPIMEREQSOURCE,
    LT_PRACCOUNT              TYPE TABLE OF BAPIMEREQACCOUNT,
    LT_PRACCOUNTPROITSEGMENT  TYPE TABLE OF BAPIMEREQACCOUNTPROFITSEG,
    LT_PRACCOUNTX             TYPE TABLE OF BAPIMEREQACCOUNTX,
    LT_PRADDRDELIVERY         TYPE TABLE OF BAPIMERQADDRDELIVERY,
    LT_PRITEMTEXT             TYPE TABLE OF BAPIMEREQITEMTEXT,
    LT_PRHEADERTEXT           TYPE TABLE OF BAPIMEREQHEADTEXT,
    LT_EXTENSIONIN            TYPE TABLE OF BAPIPAREX,
    LT_EXTENSIONOUT           TYPE TABLE OF BAPIPAREX,
    LT_PRVERSION              TYPE TABLE OF BAPIMEREQDCM,
    LT_PRVERSIONX             TYPE TABLE OF BAPIMEREQDCMX,
    LT_ALLVERSIONS            TYPE TABLE OF BAPIMEDCM_ALLVERSIONS,
    LT_PRCOMPONENTS           TYPE TABLE OF BAPIMEREQCOMPONENT,
    LT_PRCOMPONENTSX          TYPE TABLE OF BAPIMEREQCOMPONENTX,
    LT_SERVICEOUTLINE         TYPE TABLE OF BAPI_SRV_OUTLINE,
    LT_SERVICEOUTLINEX        TYPE TABLE OF BAPI_SRV_OUTLINEX,
    LT_SERVICELINES           TYPE TABLE OF BAPI_SRV_SERVICE_LINE,
    LT_SERVICELINESX          TYPE TABLE OF BAPI_SRV_SERVICE_LINEX,
    LT_SERVICELIMIT           TYPE TABLE OF BAPI_SRV_LIMIT_DATA,
    LT_SERVICELIMITX          TYPE TABLE OF BAPI_SRV_LIMIT_DATAX,
    LT_SERVICECONTRACTLIMITS  TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITS,
    LT_SERVICECONTRACTLIMITSX TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITSX,
    LT_SERVICEACCOUNT         TYPE TABLE OF BAPI_SRV_ACC_DATA,
    LT_SERVICEACCOUNTX        TYPE TABLE OF BAPI_SRV_ACC_DATAX,
    LT_SERVICELONGTEXTS       TYPE TABLE OF BAPI_SRV_LONGTEXTS,
    LT_SERIALNUMBER           TYPE TABLE OF BAPIMEREQSERIALNO,
    LT_SERIALNUMBERX          TYPE TABLE OF BAPIMEREQSERIALNOX,
    LT_RETURN                 TYPE TABLE OF BAPIRET2,
    LS_RETURN                 TYPE BAPIRET2.

  PERFORM 9004_GET_PR_CREATE_PARAMS
  USING LPT_FPAR_D
  CHANGING
      LS_PRHEADER
      LS_PRHEADERX
      LT_PRITEM
      LT_PRITEMX
      LT_PRITEMEXP
      LT_PRITEMSOURCE
      LT_PRACCOUNT
      LT_PRACCOUNTPROITSEGMENT
      LT_PRACCOUNTX
      LT_PRADDRDELIVERY
      LT_PRITEMTEXT
      LT_PRHEADERTEXT
      LT_EXTENSIONIN
      LT_EXTENSIONOUT
      LT_PRVERSION
      LT_PRVERSIONX
      LT_ALLVERSIONS
      LT_PRCOMPONENTS
      LT_PRCOMPONENTSX
      LT_SERVICEOUTLINE
      LT_SERVICEOUTLINEX
      LT_SERVICELINES
      LT_SERVICELINESX
      LT_SERVICELIMIT
      LT_SERVICELIMITX
      LT_SERVICECONTRACTLIMITS
      LT_SERVICECONTRACTLIMITSX
      LT_SERVICEACCOUNT
      LT_SERVICEACCOUNTX
      LT_SERVICELONGTEXTS
      LT_SERIALNUMBER
      LT_SERIALNUMBERX
      .

*   Create data
  CALL FUNCTION 'BAPI_PR_CREATE'
    EXPORTING
      PRHEADER               = LS_PRHEADER
      PRHEADERX              = LS_PRHEADERX
*     TESTRUN                =
    IMPORTING
      NUMBER                 = LV_NUMBER
      PRHEADEREXP            = LV_PRHEADEREXP
    TABLES
      RETURN                 = LT_RETURN
      PRITEM                 = LT_PRITEM
      PRITEMX                = LT_PRITEMX
      PRITEMEXP              = LT_PRITEMEXP
      PRITEMSOURCE           = LT_PRITEMSOURCE
      PRACCOUNT              = LT_PRACCOUNT
      PRACCOUNTPROITSEGMENT  = LT_PRACCOUNTPROITSEGMENT
      PRACCOUNTX             = LT_PRACCOUNTX
      PRADDRDELIVERY         = LT_PRADDRDELIVERY
      PRITEMTEXT             = LT_PRITEMTEXT
      PRHEADERTEXT           = LT_PRHEADERTEXT
      EXTENSIONIN            = LT_EXTENSIONIN
      EXTENSIONOUT           = LT_EXTENSIONOUT
      PRVERSION              = LT_PRVERSION
      PRVERSIONX             = LT_PRVERSIONX
      ALLVERSIONS            = LT_ALLVERSIONS
      PRCOMPONENTS           = LT_PRCOMPONENTS
      PRCOMPONENTSX          = LT_PRCOMPONENTSX
      SERVICEOUTLINE         = LT_SERVICEOUTLINE
      SERVICEOUTLINEX        = LT_SERVICEOUTLINEX
      SERVICELINES           = LT_SERVICELINES
      SERVICELINESX          = LT_SERVICELINESX
      SERVICELIMIT           = LT_SERVICELIMIT
      SERVICELIMITX          = LT_SERVICELIMITX
      SERVICECONTRACTLIMITS  = LT_SERVICECONTRACTLIMITS
      SERVICECONTRACTLIMITSX = LT_SERVICECONTRACTLIMITSX
      SERVICEACCOUNT         = LT_SERVICEACCOUNT
      SERVICEACCOUNTX        = LT_SERVICEACCOUNTX
      SERVICELONGTEXTS       = LT_SERVICELONGTEXTS
      SERIALNUMBER           = LT_SERIALNUMBER
      SERIALNUMBERX          = LT_SERIALNUMBERX.

  LPT_RETURN = LT_RETURN.
  LPW_DOCRS  = LV_NUMBER.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form 9004_GET_PR_CREATE_PARAMS
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*&      --> LPT_FPAR_D
*&      <-- LS_PRHEADER
*&      <-- LS_PRHEADERX
*&      <-- LT_PRITEM
*&      <-- LT_PRITEMX
*&      <-- LT_PRITEMEXP
*&      <-- LT_PRITEMSOURCE
*&      <-- LT_PRACCOUNT
*&      <-- LT_PRACCOUNTPROITSEGMENT
*&      <-- LT_PRACCOUNTX
*&      <-- LT_PRADDRDELIVERY
*&      <-- LT_PRITEMTEXT
*&      <-- LT_PRHEADERTEXT
*&      <-- LT_EXTENSIONIN
*&      <-- LT_EXTENSIONOUT
*&      <-- LT_PRVERSION
*&      <-- LT_PRVERSIONX
*&      <-- LT_ALLVERSIONS
*&      <-- LT_PRCOMPONENTS
*&      <-- LT_PRCOMPONENTSX
*&      <-- LT_SERVICEOUTLINE
*&      <-- LT_SERVICEOUTLINEX
*&      <-- LT_SERVICELINES
*&      <-- LT_SERVICELINESX
*&      <-- LT_SERVICELIMIT
*&      <-- LT_SERVICELIMITX
*&      <-- LT_SERVICECONTRACTLIMITS
*&      <-- LT_SERVICECONTRACTLIMITSX
*&      <-- LT_SERVICEACCOUNT
*&      <-- LT_SERVICEACCOUNTX
*&      <-- LT_SERVICELONGTEXTS
*&      <-- LT_SERIALNUMBER
*&      <-- LT_SERIALNUMBERX
*&---------------------------------------------------------------------*
FORM 9004_GET_PR_CREATE_PARAMS
  USING LPT_FPAR_D TYPE ZTT_BM_EXBA_FPAR
  CHANGING
LPS_PRHEADER TYPE  BAPIMEREQHEADER
LPS_PRHEADERX TYPE BAPIMEREQHEADERX
LPT_PRITEM TYPE TY_BAPIMEREQITEMIMP
LPT_PRITEMX TYPE TY_BAPIMEREQITEMX
LPT_PRITEMEXP TYPE TY_BAPIMEREQITEM
LPT_PRITEMSOURCE TYPE TY_BAPIMEREQSOURCE
LPT_PRACCOUNT TYPE TY_BAPIMEREQACCOUNT
LPT_PRACCOUNTPROITSEGMENT TYPE TY_BAPIMEREQACCOUNTPROFITSEG
LPT_PRACCOUNTX TYPE TY_BAPIMEREQACCOUNTX
LPT_PRADDRDELIVERY TYPE TY_BAPIMERQADDRDELIVERY
LPT_PRITEMTEXT TYPE TY_BAPIMEREQITEMTEXT
LPT_PRHEADERTEXT TYPE TY_BAPIMEREQHEADTEXT
LPT_EXTENSIONIN TYPE BAPIPAREX_TAB
LPT_EXTENSIONOUT TYPE BAPIPAREX_TAB
LPT_PRVERSION TYPE TY_BAPIMEREQDCM
LPT_PRVERSIONX TYPE TY_BAPIMEREQDCMX
LPT_ALLVERSIONS TYPE MEPO_T_BAPIMEDCM
LPT_PRCOMPONENTS TYPE TY_BAPIMEREQCOMPONENT
LPT_PRCOMPONENTSX TYPE TY_BAPIMEREQCOMPONENTX
LPT_SERVICEOUTLINE TYPE BAPI_SRV_OUTLINE_TTY
LPT_SERVICEOUTLINEX TYPE BAPI_SRV_OUTLINEX_TTY
LPT_SERVICELINES TYPE BAPI_SRV_SERVICE_LINE_TTY
LPT_SERVICELINESX TYPE BAPI_SRV_SERVICE_LINEX_TTY
LPT_SERVICELIMIT TYPE BAPI_SRV_LIMIT_DATA_TTY
LPT_SERVICELIMITX TYPE BAPI_SRV_LIMIT_DATAX_TTY
LPT_SERVICECONTRACTLIMITS TYPE BAPI_SRV_CONTRACT_LIMITS_TTY
LPT_SERVICECONTRACTLIMITSX TYPE BAPI_SRV_CONTRACT_LIMITSX_TTY
LPT_SERVICEACCOUNT TYPE BAPI_SRV_ACC_DATA_TTY
LPT_SERVICEACCOUNTX TYPE BAPI_SRV_ACC_DATAX_TTY
LPT_SERVICELONGTEXTS TYPE BAPI_SRV_LONGTEXTS_TTY
LPT_SERIALNUMBER TYPE BAPIMEREQ_T_SERIALNO
LPT_SERIALNUMBERX TYPE BAPIMEREQ_T_SERIALNOX.

  DATA:
    LR_DATA                   TYPE REF TO DATA,
    LS_PRITEMX                TYPE BAPIMEREQITEMX,
    LS_ITEM_TEXT              TYPE ZST_THEAD_ITEM,
    LS_PRACCOUNT              TYPE BAPIMEREQACCOUNT,
    LS_PRACCOUNTX             TYPE BAPIMEREQACCOUNTX,
    LS_PRVERSIONX             TYPE BAPIMEREQDCMX,
    LS_PRCOMPONENTSX          TYPE BAPIMEREQCOMPONENTX,
    LS_SERVICEOUTLINEX        TYPE BAPI_SRV_OUTLINEX,
    LS_SERVICELINESX          TYPE BAPI_SRV_SERVICE_LINEX,
    LS_SERVICELIMITX          TYPE BAPI_SRV_LIMIT_DATAX,
    LS_SERVICECONTRACTLIMITSX TYPE BAPI_SRV_CONTRACT_LIMITSX,
    LS_SERVICEACCOUNTX        TYPE BAPI_SRV_ACC_DATAX,
    LS_SERIALNUMBERX          TYPE BAPIMEREQSERIALNOX.

  LOOP AT LPT_FPAR_D INTO DATA(LPS_FPAR_D).
    CASE LPS_FPAR_D-PARAM.
      WHEN 'PRHEADER'.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LPS_PRHEADER.
      WHEN 'PRITEM'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRITEM.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRITEM.
      WHEN 'PRITEMEXP'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRITEMEXP.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRITEMEXP.
      WHEN 'PRITEMSOURCE'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRITEMSOURCE.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRITEMSOURCE.
      WHEN 'PRACCOUNT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRACCOUNT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRACCOUNT.
      WHEN 'PRACCOUNTPROITSEGMENT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRACCOUNTPROITSEGMENT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRACCOUNTPROITSEGMENT.
      WHEN 'PRADDRDELIVERY'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRADDRDELIVERY.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRADDRDELIVERY.
      WHEN 'PRITEMTEXT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRITEMTEXT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRITEMTEXT.
      WHEN 'PRHEADERTEXT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRHEADERTEXT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRHEADERTEXT.
      WHEN 'EXTENSIONIN'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_EXTENSIONIN.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_EXTENSIONIN.
      WHEN 'EXTENSIONOUT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_EXTENSIONOUT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_EXTENSIONOUT.
      WHEN 'PRVERSION'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRVERSION.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRVERSION.
      WHEN 'ALLVERSIONS'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_ALLVERSIONS.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_ALLVERSIONS.
      WHEN 'PRCOMPONENTS'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_PRCOMPONENTS.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_PRCOMPONENTS.
      WHEN 'SERVICEOUTLINE'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERVICEOUTLINE.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERVICEOUTLINE.
      WHEN 'SERVICELINES'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERVICELINES.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERVICELINES.
      WHEN 'SERVICELIMIT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERVICELIMIT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERVICELIMIT.
      WHEN 'SERVICECONTRACTLIMITS'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERVICECONTRACTLIMITS.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERVICECONTRACTLIMITS.
      WHEN 'SERVICEACCOUNT'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERVICEACCOUNT.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERVICEACCOUNT.
      WHEN 'SERVICELONGTEXTS'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERVICELONGTEXTS.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERVICELONGTEXTS.
      WHEN 'SERIALNUMBER'.
        CREATE DATA LR_DATA LIKE LINE OF LPT_SERIALNUMBER.
        CALL TRANSFORMATION ID
          SOURCE XML LPS_FPAR_D-XMLSTR
          RESULT DATA = LR_DATA->*.
        APPEND LR_DATA->* TO LPT_SERIALNUMBER.
      WHEN OTHERS.
    ENDCASE.
  ENDLOOP.

*LPS_PRHEADERX
  CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
    EXPORTING
      I_SOURCE = LPS_PRHEADER
    CHANGING
      C_DATA   = LPS_PRHEADERX.

*LPT_PRITEMX
  LOOP AT LPT_PRITEM INTO DATA(LS_PRITEM).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_PRITEM
      CHANGING
        C_DATA   = LS_PRITEMX.
    LS_PRITEMX-PREQ_ITEM = LS_PRITEM-PREQ_ITEM.
    APPEND LS_PRITEMX TO LPT_PRITEMX.
  ENDLOOP.

*LPT_PRACCOUNTX
  LOOP AT LPT_PRACCOUNT INTO LS_PRACCOUNT.
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE       = LS_PRACCOUNT
        I_TARGET_TABNM = 'BAPIMEREQACCOUNTX'
      CHANGING
        C_DATA         = LS_PRACCOUNTX.
    LS_PRACCOUNTX-PREQ_ITEM = LS_PRACCOUNT-PREQ_ITEM.
    LS_PRACCOUNTX-SERIAL_NO = LS_PRACCOUNT-SERIAL_NO.
    APPEND LS_PRACCOUNTX TO LPT_PRACCOUNTX.
  ENDLOOP.

*LPT_PRVERSIONX
  LOOP AT LPT_PRVERSION INTO DATA(LS_PRVERSION).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_PRVERSION
      CHANGING
        C_DATA   = LS_PRVERSIONX.
    LS_PRVERSIONX-PREQ_ITEM = LS_PRVERSION-PREQ_ITEM.
    APPEND LS_PRVERSIONX TO LPT_PRVERSIONX.
  ENDLOOP.

*LPT_PRCOMPONENTSX
  LOOP AT LPT_PRCOMPONENTS INTO DATA(LS_PRCOMPONENTS).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_PRCOMPONENTS
      CHANGING
        C_DATA   = LS_PRCOMPONENTSX.
    LS_PRCOMPONENTSX-PREQ_ITEM = LS_PRCOMPONENTS-PREQ_ITEM.
    LS_PRCOMPONENTSX-ITEM_NO = LS_PRCOMPONENTS-ITEM_NO.
    APPEND LS_PRCOMPONENTSX TO LPT_PRCOMPONENTSX.
  ENDLOOP.

*LPT_SERVICEOUTLINEX
  LOOP AT LPT_SERVICEOUTLINE INTO DATA(LS_SERVICEOUTLINE).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_SERVICEOUTLINE
      CHANGING
        C_DATA   = LS_SERVICEOUTLINEX.
    LS_SERVICEOUTLINEX-DOC_ITEM = LS_SERVICEOUTLINE-DOC_ITEM.
    APPEND LS_SERVICEOUTLINEX TO LPT_SERVICEOUTLINEX.
  ENDLOOP.

*LPT_SERVICELINESX
  LOOP AT LPT_SERVICELINESX INTO DATA(LS_SERVICELINES).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_SERVICELINES
      CHANGING
        C_DATA   = LS_SERVICELINESX.
    LS_SERVICELINESX-DOC_ITEM = LS_SERVICELINES-DOC_ITEM.
    APPEND LS_SERVICELINESX TO LPT_SERVICELINESX.
  ENDLOOP.

*LPT_SERVICELIMITX
  LOOP AT LPT_SERVICELIMIT INTO DATA(LS_SERVICELIMIT).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_SERVICELIMIT
      CHANGING
        C_DATA   = LS_SERVICELIMITX.
    LS_SERVICELIMITX-DOC_ITEM = LS_SERVICELIMIT-DOC_ITEM.
    APPEND LS_SERVICELIMITX TO LPT_SERVICELIMITX.
  ENDLOOP.

*LPT_SERVICECONTRACTLIMITSX
  LOOP AT LPT_SERVICECONTRACTLIMITSX INTO DATA(LS_SERVICECONTRACTLIMITS).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_SERVICECONTRACTLIMITS
      CHANGING
        C_DATA   = LS_SERVICECONTRACTLIMITSX.
    LS_SERVICECONTRACTLIMITSX-DOC_ITEM = LS_SERVICECONTRACTLIMITS-DOC_ITEM.
    LS_SERVICECONTRACTLIMITSX-CONTRACT = LS_SERVICECONTRACTLIMITS-CONTRACT.
    LS_SERVICECONTRACTLIMITSX-CONTRACT_ITEM = LS_SERVICECONTRACTLIMITS-CONTRACT_ITEM.
    APPEND LS_SERVICECONTRACTLIMITSX TO LPT_SERVICECONTRACTLIMITSX.
  ENDLOOP.

*LPT_SERVICEACCOUNTX
  LOOP AT LPT_SERVICEACCOUNT INTO DATA(LS_SERVICEACCOUNT).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_SERVICEACCOUNT
      CHANGING
        C_DATA   = LS_SERVICEACCOUNTX.
    LS_SERVICEACCOUNTX-DOC_ITEM = LS_SERVICEACCOUNT-DOC_ITEM.
    LS_SERVICEACCOUNTX-OUTLINE = LS_SERVICEACCOUNT-OUTLINE.
    LS_SERVICEACCOUNTX-SRV_LINE = LS_SERVICEACCOUNT-SRV_LINE.
    LS_SERVICEACCOUNTX-SERIAL_NO = LS_SERVICEACCOUNT-SERIAL_NO.
    APPEND LS_SERVICEACCOUNTX TO LPT_SERVICEACCOUNTX.
  ENDLOOP.

*LPT_SERIALNUMBERX
  LOOP AT LPT_SERIALNUMBER INTO DATA(LS_SERIALNUMBER).
    CALL FUNCTION 'ZFM_DATA_SET_MARK_FR_SOURCE'
      EXPORTING
        I_SOURCE = LS_SERIALNUMBER
      CHANGING
        C_DATA   = LS_SERIALNUMBERX.
    LS_SERIALNUMBERX-PREQ_ITEM = LS_SERIALNUMBER-PREQ_ITEM.
    LS_SERIALNUMBERX-PREQ_ITEMX = 'X'.
    APPEND LS_SERIALNUMBERX TO LPT_SERIALNUMBERX.
  ENDLOOP.


  " Conversion Material in PRITEM
  LOOP AT LPT_PRITEM ASSIGNING FIELD-SYMBOL(<LFS_PRITEM>).
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT  = <LFS_PRITEM>-MATERIAL
      IMPORTING
        OUTPUT = <LFS_PRITEM>-MATERIAL.
  ENDLOOP.
ENDFORM.
